import {
  Bed, Utensils, Shirt, Bath, Footprints, MoonStar,
  Smile, Sparkles, Brush, Scissors, Apple, BookOpen,
  Music, Heart, Backpack, Hand, PackageOpen, ChefHat,
  Toilet, ShowerHead, GlassWater, Milk, Banana, Sandwich,
  Pill, Sun, Star, Palette, Pencil, Puzzle, Bike, Dumbbell,
  Trophy, AlarmClock, Flower2, Gamepad2, WandSparkles, Egg,
  Cookie, IceCreamCone, Flame, Fish, Bird, Snowflake, Salad,
  Pizza, CupSoda, BicepsFlexed, Baby,
  type LucideProps,
} from 'lucide-react';
import type { FC } from 'react';

const iconMap: Record<string, FC<LucideProps>> = {
  bed: Bed,
  utensils: Utensils,
  shirt: Shirt,
  bath: Bath,
  footprints: Footprints,
  'moon-star': MoonStar,
  smile: Smile,
  sparkles: Sparkles,
  brush: Brush,
  scissors: Scissors,
  apple: Apple,
  'book-open': BookOpen,
  music: Music,
  heart: Heart,
  backpack: Backpack,
  hand: Hand,
  'package-open': PackageOpen,
  'chef-hat': ChefHat,
  // New icons
  toilet: Toilet,
  'shower-head': ShowerHead,
  'glass-water': GlassWater,
  milk: Milk,
  banana: Banana,
  sandwich: Sandwich,
  pill: Pill,
  sun: Sun,
  star: Star,
  palette: Palette,
  pencil: Pencil,
  puzzle: Puzzle,
  bike: Bike,
  dumbbell: Dumbbell,
  trophy: Trophy,
  'alarm-clock': AlarmClock,
  flower: Flower2,
  gamepad: Gamepad2,
  wand: WandSparkles,
  egg: Egg,
  cookie: Cookie,
  'ice-cream': IceCreamCone,
  flame: Flame,
  fish: Fish,
  bird: Bird,
  snowflake: Snowflake,
  salad: Salad,
  pizza: Pizza,
  'cup-soda': CupSoda,
  'biceps-flexed': BicepsFlexed,
  baby: Baby,
};

interface TaskIconProps extends LucideProps {
  iconKey: string;
}

export const TaskIcon = ({ iconKey, ...props }: TaskIconProps) => {
  const Icon = iconMap[iconKey] || Smile;
  return <Icon {...props} />;
};

const iconColorMap: Record<string, string> = {
  bed: '#94A3B8',
  utensils: '#FCD34D',
  shirt: '#93C5FD',
  bath: '#7DD3FC',
  footprints: '#A3A3A3',
  'moon-star': '#818CF8',
  smile: '#FDE047',
  sparkles: '#FCD34D',
  brush: '#A78BFA',
  scissors: '#F9A8D4',
  apple: '#F87171',
  'book-open': '#6EE7B7',
  music: '#818CF8',
  heart: '#F87171',
  backpack: '#FB923C',
  hand: '#6EE7B7',
  'package-open': '#D97706',
  'chef-hat': '#FB923C',
  toilet: '#60A5FA',
  'shower-head': '#67E8F9',
  'glass-water': '#7DD3FC',
  milk: '#E2E8F0',
  banana: '#FDE047',
  sandwich: '#FDBA74',
  pill: '#FCA5A5',
  sun: '#FDE047',
  star: '#FCD34D',
  palette: '#F472B6',
  pencil: '#FDE047',
  puzzle: '#A78BFA',
  bike: '#22D3EE',
  dumbbell: '#FDBA74',
  trophy: '#EAB308',
  'alarm-clock': '#FB923C',
  flower: '#F472B6',
  gamepad: '#60A5FA',
  wand: '#C084FC',
  egg: '#FEF08A',
  cookie: '#D97706',
  'ice-cream': '#F9A8D4',
  flame: '#FB923C',
  fish: '#22D3EE',
  bird: '#60A5FA',
  snowflake: '#BAE6FD',
  salad: '#86EFAC',
  pizza: '#F87171',
  'cup-soda': '#FCA5A5',
  'biceps-flexed': '#FDBA74',
  baby: '#F9A8D4',
};

export const getTaskIconColor = (iconKey: string): string =>
  iconColorMap[iconKey] ?? '#FCD34D';
